CREATE DATABASE TIMAVE;
USE TIMAVE;
CREATE TABLE USERS(
    USER_ID VARCHAR(255) PRIMARY KEY,
    USER_FULL_NAME VARCHAR(255) NOT NULL,
    USER_PHONE_NUMBER VARCHAR(255) NOT NULL,
    USER_EMAIL_ADDRESS VARCHAR(255) NOT NULL,
    PROFILE_PICTURE VARCHAR(255) NOT NULL,
    USER_PASSWORD VARCHAR(255) NOT NULL,
    JOINED_DATE DATE DEFAULT CURRENT_TIMESTAMP()
);
CREATE TABLE ONLINE_STATUS(
    STATUS_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(255) NOT NULL,
    ENTRY_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    USER_STATUS VARCHAR(255),
    EXIT_TIME VARCHAR(255)
);
CREATE TABLE CART(
    CART_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    USER_ID VARCHAR(255) NOT NULL,
    ITEM_ID VARCHAR(255) NOT NULL,
    QUANTITY VARCHAR(10) NOT NULL,
    CART_DATE DATE DEFAULT CURRENT_TIMESTAMP()
);
CREATE TABLE PURCHASE(
    PURCHASE_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    ITEM_ID VARCHAR(255) NOT NULL,
    QUANTITY INT,
    SELLER_ID VARCHAR(255) NOT NULL,
    USER_ID VARCHAR(255) NOT NULL,
    USER_ADDRESS VARCHAR(255) NOT NULL,
    USER_DISTRICT VARCHAR(255) NOT NULL,
    USER_PROVINCE VARCHAR(255) NOT NULL,
    USER_POSTAL VARCHAR(255) NOT NULL,
    PURCHASE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    PURCHASE_STATUS  VARCHAR(255) NOT NULL
);
CREATE TABLE ITEM(
    ITEM_ID VARCHAR(255) NOT NULL PRIMARY KEY,
    USER_ID VARCHAR(255) NOT NULL,
    ITEM_NAME VARCHAR(255) NOT NULL,
    ITEM_DESCRIPTION VARCHAR(1000) NOT NULL,
    ITEM_PRICE INT NOT NULL,
    ITEM_QUANTITY INT NOT NULL,
    ITEM_PICTURE VARCHAR(255),
    POST_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE SELLER(
    USER_ID VARCHAR(255)  PRIMARY KEY,
    USER_FULL_NAME VARCHAR(255) NOT NULL,
    USER_PHONE_NUMBER VARCHAR(255) NOT NULL,
    USER_EMAIL_ADDRESS VARCHAR(255) NOT NULL,
    PROFILE_PICTURE VARCHAR(255) NOT NULL,
    USER_PASSWORD VARCHAR(255) NOT NULL,
    JOINED_DATE DATE DEFAULT CURRENT_TIMESTAMP()
);
CREATE TABLE COMMISSION(
   USER_ID VARCHAR(255) PRIMARY KEY,
   COMMISSION_AMOUNT INT DEFAULT 0 
);
CREATE TABLE ADMIN(
    ADMIN_ID VARCHAR(255) PRIMARY KEY NOT NULL,
    ADMIN_PASSWORD VARCHAR(255) NOT NULL
);
CREATE TABLE TRANSACTION_HISTORT(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(255) NOT NULL,
    TRANSACTION_TYPE VARCHAR(255) NOT NULL,
    TRANSACTION_AMOUNT INT NOT NULL,
    TRANSACTION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
CREATE TABLE APP_COMMISSION(
    ID INT PRIMARY KEY DEFAULT 1,
    COMMISSION_AMOUNT INT DEFAULT 0
);
INSERT INTO APP_COMMISSION (ID) VALUES(1);
CREATE TABLE CUSTOM_SHIRT(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(255) NOT NULL,
    SHIRT_SIZE VARCHAR(255) NOT NULL,
    CUSTOM_PICTURE VARCHAR(255),
    PRINT_SIZE VARCHAR(255) NOT NULL,
    CUSTOM_TEXT VARCHAR(255) NOT NULL,
    SHIRT_COLOR VARCHAR(255) NOT NULL,
    CUSTOM_DATE DATE DEFAULT CURRENT_TIMESTAMP() 
);